### ISSUE TITLE
useLocalization undefined in wrapRootElement

### ISSUE THREAD

**Issue by pi0neerpat** [herecydev/gatsby-plugin-internationalization#2]
After looking through all the gatsby localization plugins, they were all so opinionated/complex! I'm very happy you created this one, since its just what I needed. Thank you! :)

## Error

`useLocalization` works everywhere, except in `wrapRootElement` for `gatsby-browser.js`. 

Getting error `_useLocalization is undefined` in the layout.js component.

```
  System:
    OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i7-2620M CPU @ 2.70GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.15.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
  Languages:
    Python: 2.7.12 - /usr/bin/python
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.21.22 => 2.21.22
    gatsby-image: ^2.4.3 => 2.4.3
    gatsby-plugin-internationalization: ^0.10.0 => 0.10.0
    gatsby-plugin-manifest: ^2.4.2 => 2.4.2
    gatsby-plugin-offline: ^3.2.1 => 3.2.1
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-sharp: ^2.6.2 => 2.6.2
    gatsby-source-filesystem: ^2.3.1 => 2.3.1
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.10.9
```
 
## Expected behavior

I wrap all pages with Layout using `wrapRootElement`. I  expect to be able to use the hook `useLocalization` and `localizedNavigate` in my Layout for navigation. 

I'm not using `gatsby-ssr.js` so I expected I could still use a react hook here.

## Reproduce error

I used the Gatsby starter template and put `useLocalization` in both `/page/index.js` (works here) and the `gatsby-browser` (doesn't work here).

https://github.com/pi0neerpat/test-plugin-internationalization

**Comment by herecydev** [comment]
Hi Patrick 👋, thanks for reaching out. That looks very expected to me, all the information about location and pages that Gatsby provides is **after** the root element. Which means the earliest opportunity to consume this information is at the `wrapPageElement` point, which is what the plugin uses to provide that information.

I can see what you're doing with the layout component, the easy fix is to use `wrapPageElement` instead of `wrapRootElement` as this will then have access to the pageContext (which includes the locale information).

One argument I can give about using `wrapRootElement` is that you will never be able to localize the layout component anyway, for example the button text:

```jsx
<button onClick={onClick}>
  localization navigation (doesn't work)
</button>
```

You would ideally want this text to be localized for the different languages (which requires the pageContext information). So the following should work:

```jsx
//gatsby-browser.js
import { LocalizationProvider } from "gatsby-plugin-internationalization"

export const wrapPageElement = ({ element, props }) => {
  return (
    <LocalizationProvider {...props}> //add another provider so the layout component can also use it
      <Layout>{element}</Layout>
    </LocalizationProvider>
  )
}
```

And your layout components are now aware of localization too:

```jsx
const { localizedNavigate, locale } = useLocalization()

<button onClick={onClick}>
  {locale != "fr" ? "localization navigation works" : "and also in french"}
</button>
```


Hope that explains a few things, let me know if you need any further help.

**Comment by pi0neerpat** [comment]
Wow thanks for the awesome reply! Looking forward to testing this out and will report back here. You rock!

**Comment by pi0neerpat** [comment]
It works! I updated the repo with the fix if anyone comes here later.

I didn't even know `wrapPageEelement` exists. And even more useful is that `page context` is available here. Now I can easily do fun stuff like updating the path based on `i18next-browser-languagedetector`

Thanks again!

**Comment by pi0neerpat** [comment]
Also I see you've already added docs!

**Comment by herecydev** [comment]
Thanks for the feedback, I'll be publishing a release shortly that will give you a much cleaner error message if you run into this issue.
